### ISSUE TITLE
Library scan fails on foreign server

### ISSUE THREAD

**Issue by empaa** [PJnes/cmcucp#10]
Thanks for an awesome little script! I have a suggestion, hope it’s fine that I post it here as it’s also a solution to a problem for all us non English speaking fans.
It would be great if the library section names could be passed as argument to support media servers running other languages than English. Easy to fix locally just swapping Movies for, let’s say Filmer which is the Swedish name of that section in the py file, but it would be amazing if this was passed as arguments so that one could always just run the most up to date docker image when adding content to the library. Keep up the good work!

**Comment by PJnes** [comment]
I've pushed a branch that should fix this issue for you @empaa, without having to specify the library names. Should also handle multiple libraries as well.

Could you give it a test? Instructions are in the pull request #11

**Comment by empaa** [comment]
Thank you, works great! I’m an absolute noob at github so I’m sorry for posting and deleting but this solves this problem indeed.
