### ISSUE TITLE
Some series titles are not prepended with “Marvel’s”

### ISSUE THREAD

**Issue by empaa** [PJnes/cmcucp#12]
After pull request #11 when the library’s are found and things are actually being added I spotted another peculiar issue concerning the tv shows matching. I don’t know if this is a localization problem in my Plex metadata (Swedish library with original titles always) or if it’s something else but the titles of newer shows like Falcon and WandaVision are not prepended with “Marvel’s” in my library and therefore they are not matched by the script. Shows like The Defenders and Agents of SHIELD are however prepended with Marvel’s and are added as expected. I tried a lazy fix and commented out the renaming on line 40 (show = "Marvel's %(show)s" % {'show': show}) and that actually worked, all four shows being matched and added. Now, I don’t know if there’s a specific reason to prepend Marvel’s to all the titles, maybe some shows get mixed up in the matching with other, non marvel series or something. If that’s the case maybe an acceptable solution could be to try match “Marvel’s %(show)s” first and if that fails attempt to match only “show” before throwing the no match error.

Edit:
If this is a localization problem it was an extremely easy fix to just add Marvel’s to the titles manually in the Plex library. Then the docker way of doing this works beautifully.

**Comment by PJnes** [comment]
I think this is my own laziness catching up with me. When I first created this, all the TV shows had 'Marvels' in front, but the new Disney+ ones don't. I think I'm just going to have to copy and paste a bunch :D

**Comment by PJnes** [comment]
Should be sorted now. I've just added the "Marvel's" to the shows that should have it.

**Comment by empaa** [comment]
You sir, legend! 🕺
